var hierarchy =
[
    [ "koutil::container::hash_array< Key, KeyID, KeyAdapter, Hash, Bucket, Allocator >::adapter_wrapper", "d0/d14/structkoutil_1_1container_1_1hash__array_1_1adapter__wrapper.html", null ],
    [ "koutil::args::argument_t< Result >", "d6/dc4/classkoutil_1_1args_1_1argument__t.html", null ],
    [ "koutil::term::color_bg_t", "de/df5/structkoutil_1_1term_1_1color__bg__t.html", null ],
    [ "koutil::term::color_fg_t", "db/d1f/structkoutil_1_1term_1_1color__fg__t.html", null ],
    [ "koutil::term::color_t", "d1/d7e/structkoutil_1_1term_1_1color__t.html", null ],
    [ "koutil::args::command_builder_t< Result >", "dd/dc3/classkoutil_1_1args_1_1command__builder__t.html", null ],
    [ "koutil::args::command_t< extends_result >", "d9/d8c/classkoutil_1_1args_1_1command__t.html", null ],
    [ "koutil::args::command_t< result_t >", "d9/d8c/classkoutil_1_1args_1_1command__t.html", null ],
    [ "koutil::args::command_t< result_t >< result_t >", "d9/d8c/classkoutil_1_1args_1_1command__t.html", null ],
    [ "koutil::container::comptime_map< Key, Value, Size >", "d2/d7d/classkoutil_1_1container_1_1comptime__map.html", null ],
    [ "koutil::type::types_transforms::constant", "d7/da3/structkoutil_1_1type_1_1types__transforms_1_1constant.html", null ],
    [ "koutil::type::types_transforms::constant_reference", "da/d65/structkoutil_1_1type_1_1types__transforms_1_1constant__reference.html", null ],
    [ "koutil::term::cursor_move", "dc/d9b/structkoutil_1_1term_1_1cursor__move.html", null ],
    [ "koutil::term::cursor_pos", "dd/d70/structkoutil_1_1term_1_1cursor__pos.html", null ],
    [ "koutil::term::dimensions_t", "dd/da7/structkoutil_1_1term_1_1dimensions__t.html", null ],
    [ "std::false_type", null, [
      [ "koutil::type::are_types< T >", "dd/de2/structkoutil_1_1type_1_1are__types.html", null ]
    ] ],
    [ "koutil::container::hash_array< Key, KeyID, KeyAdapter, Hash, Bucket, Allocator >", "d2/dd7/classkoutil_1_1container_1_1hash__array.html", null ],
    [ "koutil::container::hash_array< Key, KeyID, KeyAdapter, Hash, Bucket, Allocator >::hash_wrapper", "d5/daa/structkoutil_1_1container_1_1hash__array_1_1hash__wrapper.html", null ],
    [ "koutil::args::help_printer_t< Result >", "d1/d44/classkoutil_1_1args_1_1help__printer__t.html", null ],
    [ "koutil::container::multi_vector< Types >::iterator< is_const >", "d1/daa/classkoutil_1_1container_1_1multi__vector_1_1iterator.html", null ],
    [ "koutil::container::template_hash_array< Key, KeyID, ComptimeData, KeyAdapter, Hash, Bucket, Allocator >::iterator< is_const >", "d2/d4e/classkoutil_1_1container_1_1template__hash__array_1_1iterator.html", null ],
    [ "koutil::container::multi_vector< Types >", "dc/da1/classkoutil_1_1container_1_1multi__vector.html", null ],
    [ "koutil::args::option_builder_t< Result >", "df/dd5/classkoutil_1_1args_1_1option__builder__t.html", null ],
    [ "koutil::args::option_data_t", "d2/d7e/structkoutil_1_1args_1_1option__data__t.html", null ],
    [ "koutil::args::option_t< Result >", "d3/d31/classkoutil_1_1args_1_1option__t.html", null ],
    [ "koutil::args::parser_t< Result >", "de/d03/classkoutil_1_1args_1_1parser__t.html", null ],
    [ "koutil::type::types_transforms::reference", "df/da4/structkoutil_1_1type_1_1types__transforms_1_1reference.html", null ],
    [ "koutil::args::result_base_t", "df/dfb/classkoutil_1_1args_1_1result__base__t.html", null ],
    [ "koutil::container::multi_vector< Types >::single_vector< T, Allocator >", "d4/d2e/classkoutil_1_1container_1_1multi__vector_1_1single__vector.html", null ],
    [ "koutil::container::multi_vector< Types >::single_vector_container", "da/d1d/structkoutil_1_1container_1_1multi__vector_1_1single__vector__container.html", null ],
    [ "koutil::args::command_t< extends_result >::string_hash", "db/d4f/structkoutil_1_1args_1_1command__t_1_1string__hash.html", null ],
    [ "koutil::container::template_hash_array< Key, KeyID, ComptimeData, KeyAdapter, Hash, Bucket, Allocator >", "db/d9f/classkoutil_1_1container_1_1template__hash__array.html", null ],
    [ "koutil::container::template_hash_array< key_t, key_id_t, bool, adapter_wrapper, hash_wrapper, bucket_t, allocator_t >", "db/d9f/classkoutil_1_1container_1_1template__hash__array.html", null ],
    [ "koutil::term::terminal", "d8/d3d/classkoutil_1_1term_1_1terminal.html", null ],
    [ "std::true_type", null, [
      [ "koutil::type::are_types< types< Types... > >", "d1/d68/structkoutil_1_1type_1_1are__types_3_01types_3_01Types_8_8_8_01_4_01_4.html", null ]
    ] ],
    [ "koutil::type::types_transforms::tuple", "dc/d2d/structkoutil_1_1type_1_1types__transforms_1_1tuple.html", null ],
    [ "koutil::type::types< T >", "dd/d52/structkoutil_1_1type_1_1types.html", null ],
    [ "koutil::type::types_cat< T, U >", "d0/de2/structkoutil_1_1type_1_1types__cat.html", null ],
    [ "koutil::type::types_cat< types< T... >, types< U... > >", "dd/ddb/structkoutil_1_1type_1_1types__cat_3_01types_3_01T_8_8_8_01_4_00_01types_3_01U_8_8_8_01_4_01_4.html", null ],
    [ "koutil::type::types_containers", "df/da9/structkoutil_1_1type_1_1types__containers.html", null ],
    [ "koutil::type::types_count< Types >", "d3/d40/structkoutil_1_1type_1_1types__count.html", null ],
    [ "koutil::type::types_count< types< Types... > >", "d9/d27/structkoutil_1_1type_1_1types__count_3_01types_3_01Types_8_8_8_01_4_01_4.html", null ],
    [ "koutil::type::types_transforms", "dd/d0e/structkoutil_1_1type_1_1types__transforms.html", null ],
    [ "koutil::type::types_transforms::variant", "db/de5/structkoutil_1_1type_1_1types__transforms_1_1variant.html", null ],
    [ "koutil::type::types_containers::vector", "d1/d63/structkoutil_1_1type_1_1types__containers_1_1vector.html", null ],
    [ "koutil::type::types_transforms::vector_const_reference", "dd/db8/structkoutil_1_1type_1_1types__transforms_1_1vector__const__reference.html", null ],
    [ "koutil::type::types_transforms::vector_reference", "df/df4/structkoutil_1_1type_1_1types__transforms_1_1vector__reference.html", null ]
];