name: Doxygen GitHub Pages Deploy Action

on:
    push:
        branches:
            - main
permissions:
    contents: write
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
              with:
                  submodules: true

            - name: Install Doxygen
              run: sudo apt install doxygen graphviz -y

            - name: Generate Doxygen Documentation
              run: doxygen ./Doxyfile

            - name: Deploy to Github Pages
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  branch: gh-pages
                  folder: docs/html
