name: Doxygen GitHub Pages Deploy Action

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Generate Doxygen Documentation
              uses: mattnotmitt/doxygen-action@v1.9.8

            - name: Deploy to Github Pages
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  branch: gh-pages
                  folder: docs/html
